<?php

namespace Kamedon\Bundle\AndroidToolBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StringResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StringResourceRepository extends EntityRepository
{
    public function isRegisteredLang(StringResource $stringResource)
    {
        /**
         * @var array
         */
        $res = $this->findBy(
            ['parent' => $stringResource->getParent()->getId(), 'lang' => $stringResource->getLang()]);
        return count($res) > 0;
    }

    public function getParents()
    {
        $res = $this->findBy(['parent' => null]);
        return $res;
    }
}
