<?php

namespace Kamedon\Bundle\AndroidToolBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StringResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StringResourceRepository extends EntityRepository
{
}
