<?php
namespace Kamedon\Bundle\AndroidToolBundle\Utility\Android\Resource\File;

use Kamedon\Bundle\AndroidToolBundle\Entity\AndroidString;
use Kamedon\Bundle\AndroidToolBundle\Utility\Android\Resource\AndroidLang;

/**
 * Created by IntelliJ IDEA.
 * User: kamedon
 * Date: 14/12/09
 * Time: 20:58
 */
class StringsXml extends AndroidResourceFile
{

    /** @var string */
    private $lang = AndroidLang::LANG_DEFAULT;

    /**
     * @param $path
     */
    public function __construct($path)
    {
        parent::__construct($path); // TODO: Change the autogenerated stub
        $path = explode('/', $this->path);
        preg_match("/values-?(.*)/", $path[count($path) - 1], $res);
        if (!empty($res[1])) {
            $this->lang = $res[1];
        }
    }


    /**
     * @return \Generator
     */
    public function read()
    {
        $contents = file_get_contents($this->path);
        $xml = simplexml_load_string($contents);
        foreach ($xml->string as $resource) {
            $string = new AndroidString();
            $string->setAttr((string)$resource->attributes()->name);
            $string->setValue((string)$resource);
            yield $string;
        }
    }

    /**
     * @return string
     */
    public function getLang()
    {
        return $this->lang;
    }

    /**
     * @param string $lang
     */
    public function setLang($lang)
    {
        $this->lang = $lang;
    }

}